### ISSUE TITLE
CustomScrollView in a SKSpriteNode

### ISSUE THREAD

**Issue by Commyno** [crashoverride777/Swift-SpriteKit-UIScrollView-Helper#6]
Hi dear,
i appreciate your great work. I try to implement it in my game, but i have a problem becouse i want to insert the CustomScroll in a SKSpriteNode (that is my menu in game)  and not in a SKScene. In that scenary, the Custom Class didn't retrive the correct scene and the class not instance.
Could you give me some Tips & tricks to resolve it?
Thanks a lot.

Tonight i'll put my work on Git so you can see my code. :-)
Gianni.

**Comment by crashoverride777** [comment]
Hey,

Thanks for your comments and for using this Repo. If you be so kind to send me the link to your project and I will have a look. 

Best regards

**Comment by Commyno** [comment]
Hi,
This is the link

https://github.com/Commyno/GameTower

let me know if any problem to retrive it

Thanks a lot
